// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://puaiiavqbjykripyvhvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1YWlpYXZxYmp5a3JpcHl2aHZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNzM1OTcsImV4cCI6MjA2NTY0OTU5N30.4e1cc6UfUELkeXhEp_fphREbF_8M_0cgUmjj1D7uKc8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);